import React from 'react'
import PropTypes from 'prop-types'
import DatePicker from 'react-datepicker'
import moment from 'moment'
import { Input } from '@material-ui/core'

import 'react-datepicker/dist/react-datepicker.css'
import { makeStyles } from '@material-ui/styles'

/**
 * Using Material UI makeStyles to create custom classes
 */
const useStyles = makeStyles({
	filterInput: {
		alignSelf: 'center',
	},
})

/**
 * Functional React Component which allows for custom creation
 * of the filter of type Input Date
 */
const DateFilter = ({ filter, updateQuery }) => {
	// Custom Classes generated by Material UI
	const classes = useStyles()

	const handleChange = newDate => {
		const date = moment(newDate).format('MMM Do, YYYY')
		const queryDate = moment(newDate).format('YYYY-MM-DD')
		updateQuery(date, `${filter.value}:[${queryDate} TO *]`)
	}

	return (
		<div className={classes.filterInput}>
			{filter.name}:{' '}
			<DatePicker customInput={<Input />} onChange={handleChange} />
		</div>
	)
}

DateFilter.propTypes = {
	filter: PropTypes.shape({
		name: PropTypes.string,
		value: PropTypes.string,
		type: PropTypes.string,
		isMultiple: PropTypes.bool,
	}).isRequired,
	updateQuery: PropTypes.func.isRequired,
}

export default DateFilter
